[package]
name = "hw-rtsa-sdk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hw-rtsa-sdk"
path = "src/main.rs"

[lib]
name = "hw_rtsa_sdk"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-stream = "0.1.14"
thiserror = "1.0"

[dependencies.tokio]
version = "1.17.0"
features = ["full"]

[dependencies.hw-rtsa-sdk-sys]
path = "hw-rtsa-sdk-sys"
