[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "playground"
path = "src/main.rs"

[lib]
name = "playground"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-stream = "0.1.14"

[dependencies.tokio]
version = "1.17.0"
features = ["full"]

[dependencies.hw-rtsa-sdk-sys]
path = "hw-rtsa-sdk-sys"
