[package]
name = "hw-cloud-schema"
version = "0.1.0"
edition = "2021"

[lib]
name = "hw_cloud_schema"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
all = ["ECS","GACS","FACS","BMS","DeH","AS","IMS","FunctionGraph","CVR","CPH","CMS","OBS","EVS","VBS","CSBS","SDRS","SFS","SFSTurbo","DES","LSA","CBR","DSS","DESS","DWR","MapDS","VPC","ELB","NAT","EIP","DC","VPN","VPCEP","CC","ER","GA","EC","G-EIP","RDS","DDS","DDM","DRS","DAS","NoSQL","DBS","TaurusDB","GaussDB","RDSforPostgreSQL","RDSforSQLServer","GaussDBforNoSQL","GaussDBforCassandra","GaussDBforMongo","GaussDBforRedis","GaussDBforInflux","GaussDBforopenGauss","UGO","MLS","NLP","nlplu","nlplg","nlpc","nlpmt","nlpkg","CBS","QABot","PhoneBot","cbssa","cbsc","FRS","Moderation","textmoderation","imagemoderation","Smart_Retail","Smart_Campus","Smart_Traffic","OCR","generalocr","cardocr","receiptocr","domainocr","customocr","Image","ROC","imagetagging","DLS","GES","ImageSearch","RES","iWater","iManufacturing","iTransport","iPower","iFinance","iRetail","MTS","ModelArts","HiLens","VFP","VCP","VCT","MT","ASRC","KG","VAS","SIS","LASR","TTS","RASR","ASR","NAIE","IVS","CampusGo","VCM","eiHealth","OROAS","PanguLargeModels","OptVerse","AppKit","Octopus","DIS","DWS","CSS","DLF","CS","MRS","DLI","Batch","DGC","CloudTable","DataArtsStudio","LakeFormation","TICS","DataArtsInsight","CCE","CCI","SWR","AOS","ASM","WAF","AAD","Anti-DDoS","HSS","KMS","CSMS","KPS","DBSS","SES","SA","SCM","CBH","CGS","DSC","CCM","CFW","SecMaster","BSS","CSE","APIG","Kafka","RocketMQ","RabbitMQ","DCS","DCSforRedis","DCSforMemcached","EG","MAS","CES","LTS","IAM","CTS","TMS","RTS","EPS","RMS","SMN","APM","AOM","Organizations","RAM","Config","IdentityCenter","OA","CDN","IEF","CloudPond","IEC","IES","ProjectMan","CodeHub","CloudPipeline","CodeCheck","MobileAppTest","CloudTest","Classroom","VOC","CloudIDE","CodeCraft","DevSecurity","ServiceStage","CPTS","CAE","CodeArtsArtifact","CodeArtsBuild","CodeArtsCheck","CodeArtsDeploy","CodeArtsInspector","CodeArtsPipeline","DNS","WeLink","Meeting","VoiceCall","MSGSMS","PrivateNumber","ContactCenter","FCS","CMN","ROMA","Workspace","WorkspaceApp","CMC","OMS","CDM","DRS","SMS","BCS","MPC","VOD","Live","CVCS","CloudVR","Media_AI","IVM","CloudRTC","VIS","MetaStudio","IEF","OceanBooster","IoTDP","ocv2x","OCIOV","IoTDA","OCStudio","IoTAnalytics","DRIS","IoTEdge","GSL","DCC","BMS","VGVAS","KooMessage","KooMap","EDS","MSSI","KooPhone","IDT","iDME","iDMEClassicAPI","DevStar","OpenSource","HCloud_CLI","APIExplorer","FlowCube","OSM"]
ECS = []
GACS = []
FACS = []
BMS = []
DeH = []
AS = []
IMS = []
FunctionGraph = []
CVR = []
CPH = []
CMS = []
OBS = []
EVS = []
VBS = []
CSBS = []
SDRS = []
SFS = []
SFSTurbo = []
DES = []
LSA = []
CBR = []
DSS = []
DESS = []
DWR = []
MapDS = []
VPC = []
ELB = []
NAT = []
EIP = []
DC = []
VPN = []
VPCEP = []
CC = []
ER = []
GA = []
EC = []
G-EIP = []
RDS = []
DDS = []
DDM = []
DRS = []
DAS = []
NoSQL = []
DBS = []
TaurusDB = []
GaussDB = []
RDSforPostgreSQL = []
RDSforSQLServer = []
GaussDBforNoSQL = []
GaussDBforCassandra = []
GaussDBforMongo = []
GaussDBforRedis = []
GaussDBforInflux = []
GaussDBforopenGauss = []
UGO = []
MLS = []
NLP = []
nlplu = []
nlplg = []
nlpc = []
nlpmt = []
nlpkg = []
CBS = []
QABot = []
PhoneBot = []
cbssa = []
cbsc = []
FRS = []
Moderation = []
textmoderation = []
imagemoderation = []
Smart_Retail = []
Smart_Campus = []
Smart_Traffic = []
OCR = []
generalocr = []
cardocr = []
receiptocr = []
domainocr = []
customocr = []
Image = []
ROC = []
imagetagging = []
DLS = []
GES = []
ImageSearch = []
RES = []
iWater = []
iManufacturing = []
iTransport = []
iPower = []
iFinance = []
iRetail = []
MTS = []
ModelArts = []
HiLens = []
VFP = []
VCP = []
VCT = []
MT = []
ASRC = []
KG = []
VAS = []
SIS = []
LASR = []
TTS = []
RASR = []
ASR = []
NAIE = []
IVS = []
CampusGo = []
VCM = []
eiHealth = []
OROAS = []
PanguLargeModels = []
OptVerse = []
AppKit = []
Octopus = []
DIS = []
DWS = []
CSS = []
DLF = []
CS = []
MRS = []
DLI = []
Batch = []
DGC = []
CloudTable = []
DataArtsStudio = []
LakeFormation = []
TICS = []
DataArtsInsight = []
CCE = []
CCI = []
SWR = []
AOS = []
ASM = []
WAF = []
AAD = []
Anti-DDoS = []
HSS = []
KMS = []
CSMS = []
KPS = []
DBSS = []
SES = []
SA = []
SCM = []
CBH = []
CGS = []
DSC = []
CCM = []
CFW = []
SecMaster = []
BSS = []
CSE = []
APIG = []
Kafka = []
RocketMQ = []
RabbitMQ = []
DCS = []
DCSforRedis = []
DCSforMemcached = []
EG = []
MAS = []
CES = []
LTS = []
IAM = []
CTS = []
TMS = []
RTS = []
EPS = []
RMS = []
SMN = []
APM = []
AOM = []
Organizations = []
RAM = []
Config = []
IdentityCenter = []
OA = []
CDN = []
IEF = []
CloudPond = []
IEC = []
IES = []
ProjectMan = []
CodeHub = []
CloudPipeline = []
CodeCheck = []
MobileAppTest = []
CloudTest = []
Classroom = []
VOC = []
CloudIDE = []
CodeCraft = []
DevSecurity = []
ServiceStage = []
CPTS = []
CAE = []
CodeArtsArtifact = []
CodeArtsBuild = []
CodeArtsCheck = []
CodeArtsDeploy = []
CodeArtsInspector = []
CodeArtsPipeline = []
DNS = []
WeLink = []
Meeting = []
VoiceCall = []
MSGSMS = []
PrivateNumber = []
ContactCenter = []
FCS = []
CMN = []
ROMA = []
Workspace = []
WorkspaceApp = []
CMC = []
OMS = []
CDM = []
SMS = []
BCS = []
MPC = []
VOD = []
Live = []
CVCS = []
CloudVR = []
Media_AI = []
IVM = []
CloudRTC = []
VIS = []
MetaStudio = []
OceanBooster = []
IoTDP = []
ocv2x = []
OCIOV = []
IoTDA = []
OCStudio = []
IoTAnalytics = []
DRIS = []
IoTEdge = []
GSL = []
DCC = []
VGVAS = []
KooMessage = []
KooMap = []
EDS = []
MSSI = []
KooPhone = []
IDT = []
iDME = []
iDMEClassicAPI = []
DevStar = []
OpenSource = []
HCloud_CLI = []
APIExplorer = []
FlowCube = []
OSM = []


[dependencies]
typify = { version = "*" }
serde = { version = "*", features = ["derive"] }


[build-dependencies]
reqwest = { version = "*", features = ["json"] }
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
futures = { version = "*" }