[package]
name = "hw-rtsa-sdk-sys"
version = "0.1.0"
edition = "2021"
links = "rtsaControl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69"
cmake = "0.1"
fs_extra = "1.3"